
function r = segment_stationarity(V, R)

    delta = R(:, 2) - R(:, 1);

    k = V * [delta; 0];
    b = V * [R(:, 1); 1];

    h = [ ...
        k(3) * delta, ...
        k(3) * R(:, 1) + b(3) * delta - k(1:2), ...
        b(3) * R(:, 1) - b(1:2), ...
        k(3)^2 * delta, ...
        2 * k(3) * b(3) * delta, ...
        k(3) * b(1:2) - k(1:2) * b(3) + b(3)^2 * delta];

    c = [ ...
        sum(h(:, 3) .* h(:, 6)), ...
        sum(h(:, 2) .* h(:, 6) + h(:, 3) .* h(:, 5)), ...
        sum(h(:, 1) .* h(:, 6) + h(:, 2) .* h(:, 5) + h(:, 3) .* h(:, 4)), ...
        sum(h(:, 1) .* h(:, 5) + h(:, 2) .* h(:, 4)), ...
        sum(h(:, 1) .* h(:, 4))];
    
    t = roots(c(end:-1:1));
    t = t(imag(t) == 0);
    t = t(t>0 & t<1);
    if numel(t) == 0
        r = [];
    else
        r = delta * t' + R(:, 1);
    end 
end

